language: ruby
cache: bundler
rvm:
  - 2.2.3
sudo: false
addons:
  code_climate:
    repo_token: c23b7c30686d18d55db46ced6d2a95dcf1849ace72818b4dfc7c363dfaf798b9
bundler_args: --without development
script:
  - bundle exec rspec
