# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f71b11dab40e7b7a5b69b96a004304049728e605127a720d8b929a98d6bee7fec4292b02d4346c123bfd032062051942bd75c54d792a65333589688199ad63f

test:
  secret_key_base: 7f6d9d102c7265035ac8fed89a28f5c86f1d5871b0a5c674f6574d7dff215cd8d4e195a5b3cb50111fa91bdbcb1bd8f880db2564b974f15ddaa088f1d6a67ca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
